from __future__ import annotations

import argparse
import json
from pathlib import Path

from mafin.config import OLLAMA_API_KEY_CONFIGURED, OLLAMA_HOST, get_model_route
from mafin.data.snapshot import PortfolioDataSnapshot
from mafin.graph.build import build_graph

SAMPLE_PORTFOLIO = [
    {"ticker": "PETR4", "weight": 0.30, "sector": "Energia"},
    {"ticker": "VALE3", "weight": 0.25, "sector": "Mineração"},
    {"ticker": "ITUB4", "weight": 0.25, "sector": "Financeiro"},
    {"ticker": "WEGE3", "weight": 0.20, "sector": "Industrial"},
]

SAMPLE_PROFILE = {
    "risk_tolerance": "moderate",
    "horizon": "long",
    "objective": "valorização de capital com tolerância média a drawdown",
}

# Mock determinístico de dados de mercado — substituir por yfinance no próximo passo.
SAMPLE_MARKET = {
    "PETR4": {"price": 38.50, "ma50": 39.10, "ma200": 36.20, "vol_30d": 0.28, "trend": "lateral"},
    "VALE3": {"price": 62.10, "ma50": 65.40, "ma200": 68.90, "vol_30d": 0.31, "trend": "baixa"},
    "ITUB4": {"price": 33.80, "ma50": 32.10, "ma200": 30.50, "vol_30d": 0.18, "trend": "alta"},
    "WEGE3": {"price": 41.20, "ma50": 40.50, "ma200": 38.10, "vol_30d": 0.22, "trend": "alta"},
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the current graph smoke flow.")
    parser.add_argument(
        "--route-preset",
        choices=["env", "local", "b4h", "b4r"],
        default="env",
        help="Model route preset. 'env' uses MODEL_ROUTE_PRESET, defaulting to b4r.",
    )
    parser.add_argument(
        "--no-debate",
        action="store_true",
        help="Disable Bull/Bear debate. Useful for checking the B3 path.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compile graph and print route metadata without invoking LLMs.",
    )
    parser.add_argument(
        "--snapshot",
        type=Path,
        default=None,
        help="Optional snapshot JSON generated by scripts/generate_snapshot.py.",
    )
    return parser.parse_args()


def build_initial_state(snapshot_path: Path | None) -> dict:
    if snapshot_path:
        snapshot = PortfolioDataSnapshot.model_validate_json(
            snapshot_path.read_text(encoding="utf-8")
        )
        return snapshot.to_graph_state()

    return {
        "portfolio": SAMPLE_PORTFOLIO,
        "profile": SAMPLE_PROFILE,
        "market_data": SAMPLE_MARKET,
        "analyses": [],
        "debate_rounds": [],
        "debate_status": {},
        "diagnosis": None,
    }


def main() -> None:
    args = parse_args()
    route = get_model_route(args.route_preset)
    enable_debate = not args.no_debate
    graph = build_graph(
        routes=route,
        enable_debate=enable_debate,
        variant=route.preset if enable_debate else "b3",
    )

    if args.dry_run:
        print("=" * 60)
        print("DRY RUN")
        print("=" * 60)
        print(f"graph: {type(graph).__name__}")
        print(f"debate: {'enabled' if enable_debate else 'disabled'}")
        print(f"ollama_host: {OLLAMA_HOST}")
        print(f"ollama_api_key_configured: {OLLAMA_API_KEY_CONFIGURED}")
        print(json.dumps(route.as_dict(), ensure_ascii=False, indent=2))
        return

    initial_state = build_initial_state(args.snapshot)

    result = graph.invoke(initial_state)

    print("=" * 60)
    print("ANALYSES")
    print("=" * 60)
    for a in result.get("analyses", []):
        print(f"\n[{a['role']}  ({a['model']})]")
        print(json.dumps(a["output"], ensure_ascii=False, indent=2))

    print("\n" + "=" * 60)
    print("DEBATE")
    print("=" * 60)
    debate_rounds = result.get("debate_rounds", [])
    print(f"rounds: {len(debate_rounds)}")
    if result.get("debate_status"):
        print(json.dumps(result["debate_status"], ensure_ascii=False, indent=2))

    print("\n" + "=" * 60)
    print("DIAGNOSIS")
    print("=" * 60)
    diagnosis = result.get("diagnosis")
    if diagnosis:
        print(f"\n[{diagnosis['role']}  ({diagnosis['model']})]")
        print(json.dumps(diagnosis["output"], ensure_ascii=False, indent=2))
    else:
        print("No diagnosis produced.")

    print("\n" + "=" * 60)
    print("EXECUTION")
    print("=" * 60)
    print("Route:")
    print(json.dumps(result.get("model_route", {}), ensure_ascii=False, indent=2))
    print("Summary:")
    print(json.dumps(result.get("execution_summary", {}), ensure_ascii=False, indent=2))

    print("\n" + "=" * 60)
    print("FULL STATE (debug)")
    print("=" * 60)
    print(
        json.dumps(
            {k: v for k, v in result.items() if k != "market_data"},
            ensure_ascii=False,
            indent=2,
            default=str,
        )
    )


if __name__ == "__main__":
    main()
